zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredService: '*'
  routes:
    v1-posts:
      path: /v1/post/**
      url: http://localhost:8081/v1/post/
    v1-users:
      path: /v1/user/**
      url: http://localhost:8082/v1/user/
