server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  instance:
    hostname: discovery-server
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/, http://localhost:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredService: '*'
  routes:
    v1-posts:
      path: /v1-posts/**
      serviceId: v1-posts
      stripPrefix: true
    v1-users:
      path: /v1-users/**
      serviceId: v1-users
      stripPrefix: true

