zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredService: '*'
  routes:
    v1-posts:
      path: /**
      url: http://localhost:8081/
    v1-users:
      path: /**
      url: http://localhost:8082/
